# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target '19-MukCapstoneProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 19-MukCapstoneProject
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'GooglePlaces', '4.2.0'
  
end
